#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Elaborado por: Elías Lizano, Joshua Brenes
Fecha de creación: 24/4/25 7:00p.m
Última modificación: 26/4/25 9:00p.m
Versión de Python: 3.12
"""
import funciones #Documento .py con todas las funciones creadas en los retos

print('Reto 1: Decodificar varillas, sin ER. ')
print('')
print(funciones.nomenclaturaVarillaAux("SV5S60"))
print('')
print(funciones.nomenclaturaVarillaAux("SV5S55"))
print('')
print(funciones.nomenclaturaVarillaAux("SV9S60"))
print('')
print(funciones.nomenclaturaVarillaAux("SV5S6"))
print('')
print(funciones.nomenclaturaVarillaAux("Sv5S60"))
print('')
print('Reto 1 Versión B: Decodificar varillas, con ER. ')
print('')
print(funciones.nomenclaturaVarillaAuxB("SV5S60"))
print('')
print(funciones.nomenclaturaVarillaAuxB("SV5S55"))
print('')
print(funciones.nomenclaturaVarillaAuxB("SV9S60"))
print('')
print(funciones.nomenclaturaVarillaAuxB("SV5S6"))
print('')
print(funciones.nomenclaturaVarillaAuxB("Sv5S60"))
print('')
print('Reto 2: Decodificar Memorias SD, sin ER. ')
print('')
print(funciones.nomenclaturaSDAux(''))
print('')
print(funciones.nomenclaturaSDAux('micro'))
print('')
print(funciones.nomenclaturaSDAux('MicroDU1I10'))
print('')
print(funciones.nomenclaturaSDAux('MicroSDU1I10'))
print('')
print(funciones.nomenclaturaSDAux('MicroSDXCU3II6'))
print('')
print('Reto 2 Versión B: Decodificar Memorias SD, con ER. ')
print('')
print(funciones.nomenclaturaSDAuxB(''))
print('')
print(funciones.nomenclaturaSDAuxB('micro'))
print('')
print(funciones.nomenclaturaSDAuxB('MicroDU1I10'))
print('')
print(funciones.nomenclaturaSDAuxB('MicroSDU1I10'))
print('')
print(funciones.nomenclaturaSDAuxB('MicroSDXCU3II6'))
print('')
print('Reto 3: Decodificar neúmaticos, sin ER. ')
print('')
print(funciones.DecodificarNeumáticosAux("16570R1484T"))
print('')
print(funciones.DecodificarNeumáticosAux("19555D1687V"))
print('')
print(funciones.DecodificarNeumáticosAux("19555D1687AA"))
print('')
print(funciones.DecodificarNeumáticosAux("19555B1687ZR"))
print('')
print(funciones.DecodificarNeumáticosAux("16570R1450T"))
print('')
print('Reto 3 Versión B: Decodificar neúmaticos, con ER. ')
print('')
print(funciones.DecodificarNeumáticosAuxB("16570R1484T"))
print('')
print(funciones.DecodificarNeumáticosAuxB("19555D1687V"))
print('')
print(funciones.DecodificarNeumáticosAuxB("19555D1687AA"))
print('')
print(funciones.DecodificarNeumáticosAuxB("19555B1687ZR"))
print('')
print(funciones.DecodificarNeumáticosAuxB("16570R1450T"))
print('')
print('CONSLUSIONES:')
print('')
print("""Elías Lizano Valerio
Tuve sentimientos encontrados respecto al uso de las ER, pues pese a comprender sus ventajas no pude evitar preferer el proceso que hice sin ellas. Considero que esto se debe a que no estoy acostumbrado al uso de estas y mi inexperiencia con ellas me provoco complicaciones. No obstante veo las grandes ventajas que tiene sobretodo en eficiencia del código, termino este laboratorio muy interesado en el tema y tengo la intención de seguir prácticando las ER y usarlas en futuros proyectos.""")
print('')
print('''Joshua Brenes Hernández 
La utilidad de las expresiones regulares (ER) definitivamente es muy notoria a la hora de crear un código desde cero y la versatilidad de estas, las convierten en herramientas muy provechosas pues las ER pueden ser reutilizadas en problemas similares por lo que vienen muy bien.
El verdadero problema a la hora de comparar un código sin ER con un código que si tiene, es que las ER son complicadas de implementar de forma en que a la hora de buscar una expresión regular útil para el código y poder aprovecharla a mí en lo personal sí me costó un poco, pues si hay varias cosas que pensar y quitar del código para que puedan implementarse, pero al menos en mi experiencia personal el reto #3 de “Decodificación de neumáticos” se me hizo muchísimo más sencillo una vez que “se me ocurrió” la ER el código y hasta tuve la facilidad de quitarme de encima varias líneas de código de golpe únicamente con unas 3 líneas de expresiones regulares.
En conclusión, las expresiones regulares me hicieron mucho más manejable la validación del código que haberlo hecho “a pata” y definitivamente las seguiría utilizando en más retos.''')